[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
ffi = true
fs_permissions = [
    { access = "read", path = "./out"},
    { access = "read", path = "./test/fixtures/fs/read" },
    { access = "read-write", path = "./test/fixtures/fs/write" }
]

[rpc_endpoints]
fake = "https://my-fake-rpc-url"
solana-rulz = "https://solana-rulz.gg"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
